version: "3.8"

services:
  chatbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: intelligent-chatbot:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
